#!/bin/sh
# Custom script to run at first boot
# Place your custom commands below

opkg remove --autoremove luci-app-wizard luci-app-upnp luci-app-attendedsysupgrade $(opkg list-installed | grep zh-cn | sed -e "s/\s.*$//")

uci set dhcp.@dnsmasq[0].port='54'
uci commit dhcp

# Fix aria2 start issue. Refer https://github.com/aria2/aria2/issues/2152#issuecomment-2685168902
sed -i -e 's/section" log/section" log\n        procd_add_jail_mount "\/usr\/lib" #fix "errorCode=1 OSSL_PROVIDER_load 'legacy' failed"/g' /etc/init.d/aria2

# Add custom openwrt custom feeds
if ! grep -q "src/gz openwrt_packages" /etc/opkg/customfeeds.conf; then
    echo "src/gz openwrt_packages https://downloads.openwrt.org/releases/$OPENWRT_PACKAGE_VERSION/packages/aarch64_cortex-a53/packages" >> /etc/opkg/customfeeds.conf
fi
if ! grep -q "src/gz openwrt_luci" /etc/opkg/customfeeds.conf; then
    echo "src/gz openwrt_luci https://downloads.openwrt.org/releases/$OPENWRT_PACKAGE_VERSION/packages/aarch64_cortex-a53/luci" >> /etc/opkg/customfeeds.conf
fi
# Remove admin status link file
rm -rf  /usr/lib/lua/luci/view/admin_status/index/links.htm

exit 0
