#!/bin/sh
# Custom script to run at first boot
# Place your custom commands below

opkg remove --autoremove luci-app-wizard luci-app-upnp $(opkg list-installed | grep zh-cn | sed -e "s/\s.*$//")
# echo '#!/bin/sh /etc/rc.common

# # Copyright 2020 Google LLC.
# # Copyright (C) 2021 CZ.NIC z.s.p.o. (https://www.nic.cz/)
# # SPDX-License-Identifier: Apache-2.0

# USE_PROCD=1
# START=80

# start_service() {
#   local state_file
#   local port
#   local std_err std_out

#   config_load tailscale
#   config_get_bool std_out "settings" log_stdout 1
#   config_get_bool std_err "settings" log_stderr 1
#   config_get port "settings" port 41641
#   config_get state_file "settings" state_file /etc/tailscale/tailscaled.state
#   config_get fw_mode "settings" fw_mode nftables

#   /usr/sbin/tailscaled --cleanup

#   procd_open_instance
#   procd_set_param command /usr/sbin/tailscaled

#   # Starting with v1.48.1 ENV variable is required to enable use of iptables / nftables.
#   # Use nftables by default - can be changed to 'iptables' in tailscale config
#   procd_set_param env TS_DEBUG_FIREWALL_MODE="$fw_mode"

#   # Set the port to listen on for incoming VPN packets.
#   # Remote nodes will automatically be informed about the new port number,
#   # but you might want to configure this in order to set external firewall
#   # settings.
#   procd_append_param command --port "$port"
#   procd_append_param command --state "$state_file"

#   procd_set_param respawn
#   procd_set_param stdout "$std_out"
#   procd_set_param stderr "$std_err"

#   procd_close_instance
# }

# stop_service() {
#   /usr/sbin/tailscaled --cleanup
# }' > /etc/init.d/tailscale

# chmod +x /etc/init.d/tailscale

uci set dhcp.@dnsmasq[0].port='54'
uci commit dhcp

# Fix aria2 start issue. Refer https://github.com/aria2/aria2/issues/2152#issuecomment-2685168902
sed -i -e 's/section" log/section" log\n        procd_add_jail_mount "\/usr\/lib" #fix "errorCode=1 OSSL_PROVIDER_load 'legacy' failed"/g' /etc/init.d/aria2

# Add custom openwrt custom feeds
echo "src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.4/packages/aarch64_cortex-a53/packages
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.4/packages/aarch64_cortex-a53/luci" >> /etc/opkg/customfeeds.conf

exit 0