name: Router firmware image builder

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      BUILD_CUSTOM_PACKAGE:
        description: Build custom package inside "custom-packages"
        type: boolean
        default: false
      CUSTOM_PACKAGE_NAMES:
        description: Name of all custom package inside "custom-packages"
        default: luci-app-argon-config luci-theme-argon
      UPLOAD_SYSUPGRADE_ONLY:
        description: Save sysupgrade only artifact
        type: boolean
        default: true
      IMMORTALWRT_DOWNLOAD_URL:
        description: Immortalwrt base download url
        default: https://downloads.immortalwrt.org/releases
      IMMORTALWRT_VERSION:
        description: Immortalwrt version
        default: 24.10.1
      IMMORTALWRT_TARGET:
        description: Immortalwrt target to build
        default: ramips/mt7621
      IMMORTALWRT_PROFILE:
        description: Immortalwrt device profile name
        default: jcg_q20
      IMMORTALWRT_PACKAGES:
        description: Pre install package to openwrt
        default: base-files busybox ca-bundle cgi-io curl ddns-scripts ddns-scripts-cloudflare ddns-scripts-services dnsmasq-full dropbear firewall4 fstools fwtool getrandom hostapd-common htop ip-tiny ip6tables-nft ip6tables-zz-legacy ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-nft iptables-zz-legacy iw iwinfo jansson jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-des kmod-crypto-gcm kmod-crypto-geniv kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-hw-eip93 kmod-crypto-kpp kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha3 kmod-crypto-sha512 kmod-gpio-button-hotplug kmod-hwmon-core kmod-ifb kmod-ip6tables kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipset kmod-ipt-nat kmod-ipt-nat6 kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-lzo kmod-mac80211 kmod-mt76-connac kmod-mt76-core kmod-mt7915-firmware kmod-mt7915e kmod-nf-conncount kmod-nf-conntrack kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-nat6 kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-ppp kmod-pppoe kmod-pppox kmod-sched-cake kmod-sched-core kmod-slhc kmod-thermal kmod-udptunnel4 kmod-udptunnel6 kmod-wireguard libblobmsg-json libc libcurl libgcc libip4tc libip6tc libipset libiptext-nft libiptext libiptext6 libiwinfo-data libiwinfo libjson-c libjson-script liblua liblucihttp-lua liblucihttp-ucode liblucihttp libmnl libncurses libnftnl libnghttp2 libnl-tiny libpthread libubox libubus-lua libubus libuci libuclient libucode libudebug libxtables logd lua luci luci-app-argon-config luci-app-ddns luci-app-firewall luci-app-mwan3 luci-app-package-manager luci-app-sqm luci-base luci-compat luci-lib-base luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-lib-uqr luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-wireguard luci-ssl luci-theme-argon luci-theme-bootstrap mtd mwan3 netifd nftables-json odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoe procd procd-seccomp procd-ujail px5g-mbedtls resolveip rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode sqm-scripts tc-tiny terminfo ubi-utils uboot-envtools ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usign wifi-scripts wireguard-tools wireless-regdb wpad-basic-mbedtls xtables-legacy xtables-nft

env:
  BUILD_CUSTOM_PACKAGE: ${{github.event_name == 'push' || inputs.BUILD_CUSTOM_PACKAGE}}
  CUSTOM_PACKAGE_NAMES: ${{inputs.CUSTOM_PACKAGE_NAMES || 'luci-app-argon-config luci-theme-argon'}}
  UPLOAD_SYSUPGRADE_ONLY: ${{inputs.UPLOAD_SYSUPGRADE_ONLY || false}}
  IMMORTALWRT_DOWNLOAD_URL: ${{inputs.IMMORTALWRT_DOWNLOAD_URL || 'https://downloads.immortalwrt.org/releases'}}
  IMMORTALWRT_VERSION: ${{inputs.IMMORTALWRT_VERSION || '24.10.1'}}
  IMMORTALWRT_TARGET: ${{inputs.IMMORTALWRT_TARGET || 'ramips/mt7621'}}
  PROFILE: ${{inputs.IMMORTALWRT_PROFILE || 'jcg_q20'}}
  PACKAGES: ${{inputs.IMMORTALWRT_PACKAGES || 'base-files busybox ca-bundle cgi-io curl ddns-scripts ddns-scripts-cloudflare ddns-scripts-services dnsmasq-full dropbear firewall4 fstools fwtool getrandom hostapd-common htop ip-tiny ip6tables-nft ip6tables-zz-legacy ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-nft iptables-zz-legacy iw iwinfo jansson jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-des kmod-crypto-gcm kmod-crypto-geniv kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-hw-eip93 kmod-crypto-kpp kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha3 kmod-crypto-sha512 kmod-gpio-button-hotplug kmod-hwmon-core kmod-ifb kmod-ip6tables kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipset kmod-ipt-nat kmod-ipt-nat6 kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-lzo kmod-mac80211 kmod-mt76-connac kmod-mt76-core kmod-mt7915-firmware kmod-mt7915e kmod-nf-conncount kmod-nf-conntrack kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-nat6 kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-ppp kmod-pppoe kmod-pppox kmod-sched-cake kmod-sched-core kmod-slhc kmod-thermal kmod-udptunnel4 kmod-udptunnel6 kmod-wireguard libblobmsg-json libc libcurl libgcc libip4tc libip6tc libipset libiptext-nft libiptext libiptext6 libiwinfo-data libiwinfo libjson-c libjson-script liblua liblucihttp-lua liblucihttp-ucode liblucihttp libmnl libncurses libnftnl libnghttp2 libnl-tiny libpthread libubox libubus-lua libubus libuci libuclient libucode libudebug libxtables logd lua luci luci-app-argon-config luci-app-ddns luci-app-firewall luci-app-mwan3 luci-app-package-manager luci-app-sqm luci-base luci-compat luci-lib-base luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-lib-uqr luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-wireguard luci-ssl luci-theme-argon luci-theme-bootstrap mtd mwan3 netifd nftables-json odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoe procd procd-seccomp procd-ujail px5g-mbedtls resolveip rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode sqm-scripts tc-tiny terminfo ubi-utils uboot-envtools ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usign wifi-scripts wireguard-tools wireless-regdb wpad-basic-mbedtls xtables-legacy xtables-nft'}}
  IMAGE_BUILDER_FILE_NAME: ""
  IMAGE_BUILDER_URL: ""
  NEED_DOWNLOAD: true
  BUILD_TARGET_DIR: ""
  OUTPUT_BASE_NAME: ""
  BUILDER_FILE_EXT: ".xz"

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout if needed
        uses: actions/checkout@v4
        if: ${{ env.BUILD_CUSTOM_PACKAGE }}

      - name: Setup variables
        run: |
          IMMORTALWRT_TARGET=${{ env.IMMORTALWRT_TARGET }}
          IMMORTALWRT_TARGET_AS_NAME=${IMMORTALWRT_TARGET////-}
          IMAGE_BUILDER_FILE_NAME=immortalwrt-imagebuilder-${{ env.IMMORTALWRT_VERSION }}-${IMMORTALWRT_TARGET_AS_NAME}.Linux-x86_64
          IMAGE_BUILDER_URL=${{ env.IMMORTALWRT_DOWNLOAD_URL }}/${{ env.IMMORTALWRT_VERSION }}/targets/$IMMORTALWRT_TARGET/$IMAGE_BUILDER_FILE_NAME.tar
          CURL_OUTPUT=$(curl --HEAD ${IMAGE_BUILDER_URL}.xz)
          BUILDER_FILE_EXT=${{ env.BUILDER_FILE_EXT }}
          if [[ $(echo $CURL_OUTPUT | grep "404") != "" ]]; then
            BUILDER_FILE_EXT=".zst"
            echo "BUILDER_FILE_EXT=${BUILDER_FILE_EXT}" >> $GITHUB_ENV
          fi
          IMAGE_BUILDER_URL=${IMAGE_BUILDER_URL}${BUILDER_FILE_EXT}
          BUILD_TARGET_DIR=$IMAGE_BUILDER_FILE_NAME/bin/targets/$IMMORTALWRT_TARGET
          OUTPUT_BASE_NAME=immortalwrt-${{ env.IMMORTALWRT_VERSION }}-${IMMORTALWRT_TARGET_AS_NAME}-${{ env.PROFILE }}
          echo "IMAGE_BUILDER_FILE_NAME=${IMAGE_BUILDER_FILE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_BUILDER_URL=${IMAGE_BUILDER_URL}" >> $GITHUB_ENV
          echo "BUILD_TARGET_DIR=${BUILD_TARGET_DIR}" >> $GITHUB_ENV
          echo "OUTPUT_BASE_NAME=${OUTPUT_BASE_NAME}" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.IMAGE_BUILDER_FILE_NAME }}
          key: ${{ env.IMAGE_BUILDER_FILE_NAME }}

      - name: Check file 
        shell: bash
        run: |
          if [[ -d ${{env.IMAGE_BUILDER_FILE_NAME}} ]]; then
            echo "NEED_DOWNLOAD=false" >> $GITHUB_ENV
          else
            echo "NEED_DOWNLOAD=true" >> $GITHUB_ENV
          fi

      - name: Download and extract image builder
        if: ${{ env.NEED_DOWNLOAD == 'true' }}
        run: |
          wget ${{ env.IMAGE_BUILDER_URL }}
          IMAGE_BUILD_FILE=${{env.IMAGE_BUILDER_FILE_NAME}}.tar${{ env.BUILDER_FILE_EXT }}
          if [[ ${{ env.BUILDER_FILE_EXT }} == ".zst" ]]; then
            tar --zstd -x -f ${IMAGE_BUILD_FILE}
          else
            tar -J -x -f ${IMAGE_BUILD_FILE}
          fi

      - name: Copy custom packages and add custom package
        if: ${{ env.BUILD_CUSTOM_PACKAGE }}
        run: |
          rsync -hav custom-packages/* ${{env.IMAGE_BUILDER_FILE_NAME}}/packages/
          echo "PACKAGES=${{env.PACKAGES}} ${{env.CUSTOM_PACKAGE_NAMES}}" >> $GITHUB_ENV

      - name: Save cache
        if: ${{ env.NEED_DOWNLOAD == 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.IMAGE_BUILDER_FILE_NAME }}
          key: ${{ env.IMAGE_BUILDER_FILE_NAME }}

      - name: Build openwrt image
        run: |
          cd ${{ env.IMAGE_BUILDER_FILE_NAME }}
          make image \
          PROFILE=${{ env.PROFILE }} \
          PACKAGES="${{ env.PACKAGES }}"
          ls -lah bin/targets/${{ env.IMMORTALWRT_TARGET }}

      - name: Upload sysupgrade output
        if: ${{ github.event_name == 'workflow_dispatch' && env.UPLOAD_SYSUPGRADE_ONLY == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_BASE_NAME }}-sysupgrade
          path: |
            ${{ env.BUILD_TARGET_DIR }}/${{ env.OUTPUT_BASE_NAME }}-squashfs-sysupgrade.bin
            ${{ env.BUILD_TARGET_DIR }}/profiles.json
            ${{ env.BUILD_TARGET_DIR }}/sha256sums
          retention-days: 5

      - name: Upload all output
        if: ${{ github.event_name == 'workflow_dispatch' && env.UPLOAD_SYSUPGRADE_ONLY == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_BASE_NAME }}
          path: ${{ env.BUILD_TARGET_DIR }}
          retention-days: 5

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        if: ${{ github.event_name == 'push' }}
        with:
          name: "${{ github.ref_name }}"
          artifacts: "${{ env.BUILD_TARGET_DIR }}/*"
          body: |
            ### Build information:
            * Build target: **${{ env.IMMORTALWRT_TARGET }}**
            * Device profile: **${{ env.PROFILE }}**
            * Immortalwrt version: **${{ env.IMMORTALWRT_VERSION }}**
            * Image builder downloaded from: ${{ env.IMAGE_BUILDER_URL }}
            <details>
            <summary>Installed package</summary>

            ```
            ${{ env.PACKAGES }}
            ```
            </details>

