name: Router firmware image builder

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      BUILD_CUSTOM_PACKAGE:
        description: Build custom package inside "custom-packages"
        type: boolean
        default: false
      CUSTOM_PACKAGE_NAMES:
        description: Name of all custom package inside "custom-packages"
        default: luci-app-argon-config luci-theme-argon luci-app-alpha-config luci-theme-alpha
      UPLOAD_SYSUPGRADE_ONLY:
        description: Save sysupgrade only artifact
        type: boolean
        default: true
      IMMORALWRT_DOWNLOAD_URL:
        description: Immortalwrt base download url
        default: https://downloads.immortalwrt.org/releases
      IMMORALWRT_VERSION:
        description: Immortalwrt version
        default: 24.10.1
      IMMORALWRT_TARGET:
        description: Immortalwrt target to build
        default: mediatek/filogic
      IMMORALWRT_PROFILE:
        description: Immortalwrt device profile name
        default: cmcc_rax3000me
      IMMORALWRT_PACKAGES:
        description: Pre install package to immortalwrt
        default: adguardhome aria2 ariang attr avahi-dbus-daemon base-files block-mount busybox ca-bundle ca-certificates cgi-io coreutils coreutils-nohup curl dbus ddns-scripts ddns-scripts-cloudflare ddns-scripts-services dnsmasq-full dropbear firewall4 fstools fwtool getrandom git git-http hdparm hostapd-common htop https-dns-proxy ip-tiny ip6tables-nft ip6tables-zz-legacy ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-mod-ipsec iptables-nft iptables-zz-legacy iw iwinfo jansson jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-cbc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-deflate kmod-crypto-des kmod-crypto-echainiv kmod-crypto-gcm kmod-crypto-geniv kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-kpp kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha3 kmod-crypto-sha512 kmod-fs-exfat kmod-gpio-button-hotplug kmod-ifb kmod-ip6tables kmod-ipsec kmod-ipsec4 kmod-ipsec6 kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipsec kmod-ipt-ipset kmod-ipt-raw kmod-iptunnel4 kmod-iptunnel6 kmod-l2tp kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-zlib-deflate kmod-lib-zlib-inflate kmod-mac80211 kmod-macvlan kmod-mt76-core kmod-mt7603 kmod-mt76x02-common kmod-mt76x2 kmod-mt76x2-common kmod-nf-conncount kmod-nf-conntrack kmod-nf-conntrack-netlink kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-ppp kmod-pppoe kmod-pppol2tp kmod-pppox kmod-sched-cake kmod-sched-core kmod-scsi-core kmod-slhc kmod-tun kmod-udptunnel4 kmod-udptunnel6 kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb-storage kmod-usb-xhci-hcd kmod-usb-xhci-mtk kmod-usb3 kmod-wireguard libacl libatomic libattr libavahi-client libavahi-dbus-support libblkid libblobmsg-json libbz2 libc libcap libcares libcurl libdaemon libdbus libev libevdev libexpat libffi libgcc libgdbm libgmp libgnutls libip4tc libip6tc libipset libiptext-nft libiptext libiptext6 libiwinfo-data libiwinfo-lua libiwinfo libjson-c libjson-script libldns liblua liblucihttp-lua liblucihttp-ucode liblucihttp liblzma libmbedtls libmnl libncurses libnetfilter-conntrack libnettle libnfnetlink libnftnl libnghttp2 libnl-tiny libopenssl-conf libopenssl-legacy libopenssl libpam libpcre2 libpopt libpthread libpython3 libreadline librt libsodium libsqlite3 libstdcpp libtasn1 libtirpc libubox libubus-lua libubus libuci-lua libuci libuclient libucode libudebug libudev-zero libusb-1.0 libuuid libuv libxml2 libxtables logd lua luci luci-app-alpha-config luci-app-argon-config luci-app-aria2 luci-app-ddns luci-app-firewall luci-app-mwan3 luci-app-package-manager luci-app-samba4 luci-app-sqm luci-base luci-compat luci-lib-base luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-lib-uqr luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-wireguard luci-theme-alpha luci-theme-argon luci-theme-bootstrap mtd mwan3 nano netifd nftables-json nload odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoe ppp-mod-pppol2tp procd procd-seccomp procd-ujail px5g-mbedtls python3 python3-asyncio python3-base python3-cgi python3-cgitb python3-codecs python3-ctypes python3-dbm python3-decimal python3-distutils python3-email python3-light python3-logging python3-lzma python3-multiprocessing python3-ncurses python3-openssl python3-pip python3-pydoc python3-readline python3-sqlite3 python3-unittest python3-urllib python3-uuid python3-xml resolveip rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode rsync samba4-libs samba4-server sqm-scripts strongswan strongswan-charon strongswan-ipsec strongswan-minimal strongswan-mod-aes strongswan-mod-des strongswan-mod-gmp strongswan-mod-hmac strongswan-mod-kernel-netlink strongswan-mod-mgf1 strongswan-mod-pubkey strongswan-mod-random strongswan-mod-sha1 strongswan-mod-sha2 strongswan-mod-socket-default strongswan-mod-stroke strongswan-mod-updown strongswan-mod-vici strongswan-mod-x509 strongswan-mod-xauth-generic strongswan-mod-xcbc strongswan-swanctl tc-tiny terminfo ubi-utils ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usbids usbutils usign wifi-scripts wireguard-tools wireless-regdb xl2tpd xtables-legacy xtables-nft zlib
      DISABLED_SERVICES:
        description: List of service to disable startup
        default: adguardhome mwan3 xl2tpd https-dns-proxy ipsec swanctl

env:
  BUILD_CUSTOM_PACKAGE: ${{github.event_name == 'push' || inputs.BUILD_CUSTOM_PACKAGE}}
  CUSTOM_PACKAGE_NAMES: ${{inputs.CUSTOM_PACKAGE_NAMES || 'luci-app-argon-config luci-theme-argon luci-app-alpha-config luci-theme-alpha'}}
  UPLOAD_SYSUPGRADE_ONLY: ${{inputs.UPLOAD_SYSUPGRADE_ONLY || false}}
  IMMORALWRT_DOWNLOAD_URL: ${{inputs.IMMORALWRT_DOWNLOAD_URL || 'https://downloads.immortalwrt.org/releases'}}
  IMMORALWRT_VERSION: ${{inputs.IMMORALWRT_VERSION || '24.10.1'}}
  IMMORALWRT_TARGET: ${{inputs.IMMORALWRT_TARGET || 'mediatek/filogic'}}
  PROFILE: ${{inputs.IMMORALWRT_PROFILE || 'cmcc_rax3000me'}}
  PACKAGES: ${{inputs.IMMORALWRT_PACKAGES || 'adguardhome aria2 ariang attr avahi-dbus-daemon base-files block-mount busybox ca-bundle ca-certificates cgi-io coreutils coreutils-nohup curl dbus ddns-scripts ddns-scripts-cloudflare ddns-scripts-services dnsmasq-full dropbear firewall4 fstools fwtool getrandom git git-http hdparm hostapd-common htop https-dns-proxy ip-tiny ip6tables-nft ip6tables-zz-legacy ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-mod-ipsec iptables-nft iptables-zz-legacy iw iwinfo jansson jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-cbc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-deflate kmod-crypto-des kmod-crypto-echainiv kmod-crypto-gcm kmod-crypto-geniv kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-kpp kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha3 kmod-crypto-sha512 kmod-fs-exfat kmod-gpio-button-hotplug kmod-ifb kmod-ip6tables kmod-ipsec kmod-ipsec4 kmod-ipsec6 kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipsec kmod-ipt-ipset kmod-ipt-raw kmod-iptunnel4 kmod-iptunnel6 kmod-l2tp kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-zlib-deflate kmod-lib-zlib-inflate kmod-mac80211 kmod-macvlan kmod-mt76-core kmod-mt7603 kmod-mt76x02-common kmod-mt76x2 kmod-mt76x2-common kmod-nf-conncount kmod-nf-conntrack kmod-nf-conntrack-netlink kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-ppp kmod-pppoe kmod-pppol2tp kmod-pppox kmod-sched-cake kmod-sched-core kmod-scsi-core kmod-slhc kmod-tun kmod-udptunnel4 kmod-udptunnel6 kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb-storage kmod-usb-xhci-hcd kmod-usb-xhci-mtk kmod-usb3 kmod-wireguard libacl libatomic libattr libavahi-client libavahi-dbus-support libblkid libblobmsg-json libbz2 libc libcap libcares libcurl libdaemon libdbus libev libevdev libexpat libffi libgcc libgdbm libgmp libgnutls libip4tc libip6tc libipset libiptext-nft libiptext libiptext6 libiwinfo-data libiwinfo-lua libiwinfo libjson-c libjson-script libldns liblua liblucihttp-lua liblucihttp-ucode liblucihttp liblzma libmbedtls libmnl libncurses libnetfilter-conntrack libnettle libnfnetlink libnftnl libnghttp2 libnl-tiny libopenssl-conf libopenssl-legacy libopenssl libpam libpcre2 libpopt libpthread libpython3 libreadline librt libsodium libsqlite3 libstdcpp libtasn1 libtirpc libubox libubus-lua libubus libuci-lua libuci libuclient libucode libudebug libudev-zero libusb-1.0 libuuid libuv libxml2 libxtables logd lua luci luci-app-alpha-config luci-app-argon-config luci-app-aria2 luci-app-ddns luci-app-firewall luci-app-mwan3 luci-app-package-manager luci-app-samba4 luci-app-sqm luci-base luci-compat luci-lib-base luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-lib-uqr luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-wireguard luci-theme-alpha luci-theme-argon luci-theme-bootstrap mtd mwan3 nano netifd nftables-json nload odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoe ppp-mod-pppol2tp procd procd-seccomp procd-ujail px5g-mbedtls python3 python3-asyncio python3-base python3-cgi python3-cgitb python3-codecs python3-ctypes python3-dbm python3-decimal python3-distutils python3-email python3-light python3-logging python3-lzma python3-multiprocessing python3-ncurses python3-openssl python3-pip python3-pydoc python3-readline python3-sqlite3 python3-unittest python3-urllib python3-uuid python3-xml resolveip rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode rsync samba4-libs samba4-server sqm-scripts strongswan strongswan-charon strongswan-ipsec strongswan-minimal strongswan-mod-aes strongswan-mod-des strongswan-mod-gmp strongswan-mod-hmac strongswan-mod-kernel-netlink strongswan-mod-mgf1 strongswan-mod-pubkey strongswan-mod-random strongswan-mod-sha1 strongswan-mod-sha2 strongswan-mod-socket-default strongswan-mod-stroke strongswan-mod-updown strongswan-mod-vici strongswan-mod-x509 strongswan-mod-xauth-generic strongswan-mod-xcbc strongswan-swanctl tc-tiny terminfo ubi-utils ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usbids usbutils usign wifi-scripts wireguard-tools wireless-regdb xl2tpd xtables-legacy xtables-nft zlib'}}
  DISABLED_SERVICES:  ${{inputs.DISABLED_SERVICES || 'adguardhome mwan3 xl2tpd https-dns-proxy ipsec swanctl'}}
  IMAGE_BUILDER_FILE_NAME: ""
  IMAGE_BUILDER_URL: ""
  NEED_DOWNLOAD: true
  BUILD_TARGET_DIR: ""
  OUTPUT_BASE_NAME: ""
  BUILDER_FILE_EXT: ".xz"

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout if needed
        uses: actions/checkout@v4
        if: ${{ env.BUILD_CUSTOM_PACKAGE }}

      - name: Setup variables
        run: |
          IMMORALWRT_TARGET=${{ env.IMMORALWRT_TARGET }}
          IMMORALWRT_TARGET_AS_NAME=${IMMORALWRT_TARGET////-}
          IMAGE_BUILDER_FILE_NAME=immortalwrt-imagebuilder-${{ env.IMMORALWRT_VERSION }}-${IMMORALWRT_TARGET_AS_NAME}.Linux-x86_64
          IMAGE_BUILDER_URL=${{ env.IMMORALWRT_DOWNLOAD_URL }}/${{ env.IMMORALWRT_VERSION }}/targets/$IMMORALWRT_TARGET/$IMAGE_BUILDER_FILE_NAME.tar
          CURL_OUTPUT=$(curl --HEAD ${IMAGE_BUILDER_URL}.xz)
          BUILDER_FILE_EXT=${{ env.BUILDER_FILE_EXT }}
          if [[ $(echo $CURL_OUTPUT | grep "404") != "" ]]; then
            BUILDER_FILE_EXT=".zst"
            echo "BUILDER_FILE_EXT=${BUILDER_FILE_EXT}" >> $GITHUB_ENV
          fi
          IMAGE_BUILDER_URL=${IMAGE_BUILDER_URL}${BUILDER_FILE_EXT}
          BUILD_TARGET_DIR=$IMAGE_BUILDER_FILE_NAME/bin/targets/$IMMORALWRT_TARGET
          OUTPUT_BASE_NAME=immortalwrt-${{ env.IMMORALWRT_VERSION }}-${IMMORALWRT_TARGET_AS_NAME}-${{ env.PROFILE }}
          echo "IMAGE_BUILDER_FILE_NAME=${IMAGE_BUILDER_FILE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_BUILDER_URL=${IMAGE_BUILDER_URL}" >> $GITHUB_ENV
          echo "BUILD_TARGET_DIR=${BUILD_TARGET_DIR}" >> $GITHUB_ENV
          echo "OUTPUT_BASE_NAME=${OUTPUT_BASE_NAME}" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.IMAGE_BUILDER_FILE_NAME }}
          key: ${{ env.IMAGE_BUILDER_FILE_NAME }}

      - name: Check file 
        shell: bash
        run: |
          if [[ -d ${{env.IMAGE_BUILDER_FILE_NAME}} ]]; then
            echo "NEED_DOWNLOAD=false" >> $GITHUB_ENV
          else
            echo "NEED_DOWNLOAD=true" >> $GITHUB_ENV
          fi

      - name: Download and extract image builder
        if: ${{ env.NEED_DOWNLOAD == 'true' }}
        run: |
          wget ${{ env.IMAGE_BUILDER_URL }}
          IMAGE_BUILD_FILE=${{env.IMAGE_BUILDER_FILE_NAME}}.tar${{ env.BUILDER_FILE_EXT }}
          if [[ ${{ env.BUILDER_FILE_EXT }} == ".zst" ]]; then
            tar --zstd -x -f ${IMAGE_BUILD_FILE}
          else
            tar -J -x -f ${IMAGE_BUILD_FILE}
          fi

      - name: Copy custom packages and add custom package
        if: ${{ env.BUILD_CUSTOM_PACKAGE }}
        run: |
          rsync -hav custom-packages/* ${{env.IMAGE_BUILDER_FILE_NAME}}/packages/
          echo "PACKAGES=${{env.PACKAGES}} ${{env.CUSTOM_PACKAGE_NAMES}}" >> $GITHUB_ENV

      - name: Save cache
        if: ${{ env.NEED_DOWNLOAD == 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.IMAGE_BUILDER_FILE_NAME }}
          key: ${{ env.IMAGE_BUILDER_FILE_NAME }}

      - name: Build Immortalwrt image
        run: |
          cd ${{ env.IMAGE_BUILDER_FILE_NAME }}
          make image \
          PROFILE=${{ env.PROFILE }} \
          PACKAGES="${{ env.PACKAGES }}" \
          DISABLED_SERVICES="${{ env.DISABLED_SERVICES }}"
          ls -lah bin/targets/${{ env.IMMORALWRT_TARGET }}

      - name: Upload sysupgrade output
        if: ${{ github.event_name == 'workflow_dispatch' && env.UPLOAD_SYSUPGRADE_ONLY == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_BASE_NAME }}-sysupgrade
          path: |
            ${{ env.BUILD_TARGET_DIR }}/${{ env.OUTPUT_BASE_NAME }}-squashfs-sysupgrade.bin
            ${{ env.BUILD_TARGET_DIR }}/profiles.json
            ${{ env.BUILD_TARGET_DIR }}/sha256sums
          retention-days: 5

      - name: Upload all output
        if: ${{ github.event_name == 'workflow_dispatch' && env.UPLOAD_SYSUPGRADE_ONLY == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_BASE_NAME }}
          path: ${{ env.BUILD_TARGET_DIR }}
          retention-days: 5

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        if: ${{ github.event_name == 'push' }}
        with:
          name: "${{ github.ref_name }}"
          artifacts: "${{ env.BUILD_TARGET_DIR }}/*"
          body: |
            ### Build information:
            * Build target: **${{ env.IMMORALWRT_TARGET }}**
            * Device profile: **${{ env.PROFILE }}**
            * Immortalwrt version: **${{ env.IMMORALWRT_VERSION }}**
            * Image builder downloaded from: ${{ env.IMAGE_BUILDER_URL }}
            <details>
            <summary>Installed package</summary>

            ```
            ${{ env.PACKAGES }}
            ```
            </details>
            <details>
            <summary>Disabled services</summary>

            ```
            ${{ env.DISABLED_SERVICES }}
            ```
            </details>

