name: "Openwrt image builder"

on:
  push:
    tags:
      '*'
  workflow_dispatch:
    inputs:
      BUILD_CUSTOM_PACKAGE:
        description: Build custom package inside "custom-packages"
        type: boolean
        default: false
      CUSTOM_PACKAGE_NAMES:
        description: Name of all custom package inside "custom-packages"
        default: luci-app-argon-config luci-theme-argon wrtbwmon luci-app-wrtbwmon
      UPLOAD_SYSUPGRADE_ONLY:
        description: Save sysupgrade only artifact
        type: boolean
        default: true
      OPENWRT_DOWNLOAD_URL:
        description: Openwrt base download url
        default: https://downloads.openwrt.org/releases
      OPENWRT_VERSION:
        description: Openwrt version
        default: 23.05.3
      OPENWRT_TARGET:
        description: Openwrt target to build
        default: ramips/mt7621
      OPENWRT_PROFILE:
        description: Openwrt device profile name
        default: xiaomi_mi-router-3g
      OPENWRT_PACKAGES:
        description: Pre install package to openwrt
        default: aria2 ariang attr avahi-dbus-daemon base-files block-mount busybox ca-bundle ca-certificates cgi-io curl dbus ddns-scripts ddns-scripts-cloudflare ddns-scripts-services dnsmasq dropbear firewall4 fstools fwtool getrandom hostapd-common htop https-dns-proxy ip-tiny ip6tables-nft ip6tables-zz-legacy ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-mod-ipsec iptables-nft iptables-zz-legacy iw iwinfo jansson4 jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-cbc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-deflate kmod-crypto-des kmod-crypto-echainiv kmod-crypto-gcm kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-kpp kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha512 kmod-fs-exfat kmod-gpio-button-hotplug kmod-ifb kmod-ip6tables kmod-ipsec kmod-ipsec4 kmod-ipsec6 kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipsec kmod-ipt-ipset kmod-ipt-raw kmod-iptunnel4 kmod-iptunnel6 kmod-l2tp kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-zlib-deflate kmod-lib-zlib-inflate kmod-mac80211 kmod-macvlan kmod-mt76-core kmod-mt7603 kmod-mt76x02-common kmod-mt76x2 kmod-mt76x2-common kmod-nf-conncount kmod-nf-conntrack kmod-nf-conntrack-netlink kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-ppp kmod-pppoe kmod-pppol2tp kmod-pppox kmod-sched-cake kmod-sched-core kmod-scsi-core kmod-slhc kmod-tun kmod-udptunnel4 kmod-udptunnel6 kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb-storage kmod-usb-xhci-hcd kmod-usb-xhci-mtk kmod-usb3 kmod-wireguard libatomic1 libattr libavahi-client libavahi-dbus-support libblkid1 libblobmsg-json20230523 libc libcap libcares libcurl4 libdaemon libdbus libev libevdev libexpat libgcc1 libgmp10 libgnutls libip4tc2 libip6tc2 libipset13 libiptext-nft0 libiptext0 libiptext6-0 libiwinfo-data libiwinfo-lua libiwinfo20230701 libjson-c5 libjson-script20230523 libldns liblua5.1.5 liblucihttp-lua liblucihttp-ucode liblucihttp0 libmbedtls12 libmnl0 libncurses6 libnetfilter-conntrack3 libnettle8 libnfnetlink0 libnftnl11 libnghttp2-14 libnl-tiny1 libopenssl3 libpam libpopt0 libpthread libreadline8 librt libsodium libstdcpp6 libtasn1 libtirpc libubox20230523 libubus-lua libubus20230605 libuci-lua libuci20130104 libuclient20201210 libucode20230711 libudev-zero libusb-1.0-0 libustream-mbedtls20201210 libuuid1 libuv1  libxtables12 logd lua luci luci-app-aria2 luci-app-ddns luci-app-firewall luci-app-mwan3 luci-app-opkg luci-app-samba4 luci-app-sqm luci-base luci-compat luci-lib-base luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-wireguard luci-ssl luci-theme-bootstrap mtd mwan3 netifd nftables-json nload odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoe ppp-mod-pppol2tp procd procd-seccomp procd-ujail px5g-mbedtls resolveip rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode rsync samba4-libs samba4-server sqm-scripts strongswan strongswan-charon strongswan-ipsec strongswan-minimal strongswan-mod-aes strongswan-mod-des strongswan-mod-gmp strongswan-mod-hmac strongswan-mod-kernel-netlink strongswan-mod-mgf1 strongswan-mod-pubkey strongswan-mod-random strongswan-mod-sha1 strongswan-mod-sha2 strongswan-mod-socket-default strongswan-mod-stroke strongswan-mod-updown strongswan-mod-vici strongswan-mod-x509 strongswan-mod-xauth-generic strongswan-mod-xcbc strongswan-swanctl tc-tiny terminfo ubi-utils ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usbutils usign wireguard-tools wireless-regdb xl2tpd xtables-legacy xtables-nft zlib

env:
  BUILD_CUSTOM_PACKAGE: ${{github.event_name == 'push' || inputs.BUILD_CUSTOM_PACKAGE}}
  CUSTOM_PACKAGE_NAMES: ${{inputs.CUSTOM_PACKAGE_NAMES || 'luci-app-argon-config luci-theme-argon wrtbwmon luci-app-wrtbwmon'}}
  UPLOAD_SYSUPGRADE_ONLY: ${{inputs.UPLOAD_SYSUPGRADE_ONLY || false}}
  OPENWRT_DOWNLOAD_URL: ${{inputs.OPENWRT_DOWNLOAD_URL || 'https://downloads.openwrt.org/releases'}}
  OPENWRT_VERSION: ${{inputs.OPENWRT_VERSION || '23.05.3'}}
  OPENWRT_TARGET: ${{inputs.OPENWRT_TARGET || 'ramips/mt7621'}}
  PROFILE: ${{inputs.OPENWRT_PROFILE || 'xiaomi_mi-router-3g'}}
  PACKAGES: ${{inputs.OPENWRT_PACKAGES || 'aria2 ariang attr avahi-dbus-daemon base-files block-mount busybox ca-bundle ca-certificates cgi-io curl dbus ddns-scripts ddns-scripts-cloudflare ddns-scripts-services dnsmasq dropbear firewall4 fstools fwtool getrandom hostapd-common htop https-dns-proxy ip-tiny ip6tables-nft ip6tables-zz-legacy ipset iptables-mod-conntrack-extra iptables-mod-ipopt iptables-mod-ipsec iptables-nft iptables-zz-legacy iw iwinfo jansson4 jshn jsonfilter kernel kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-authenc kmod-crypto-cbc kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-deflate kmod-crypto-des kmod-crypto-echainiv kmod-crypto-gcm kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-kpp kmod-crypto-lib-chacha20 kmod-crypto-lib-chacha20poly1305 kmod-crypto-lib-curve25519 kmod-crypto-lib-poly1305 kmod-crypto-manager kmod-crypto-md5 kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha1 kmod-crypto-sha256 kmod-crypto-sha512 kmod-fs-exfat kmod-gpio-button-hotplug kmod-ifb kmod-ip6tables kmod-ipsec kmod-ipsec4 kmod-ipsec6 kmod-ipt-conntrack kmod-ipt-conntrack-extra kmod-ipt-core kmod-ipt-ipopt kmod-ipt-ipsec kmod-ipt-ipset kmod-ipt-raw kmod-iptunnel4 kmod-iptunnel6 kmod-l2tp kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-zlib-deflate kmod-lib-zlib-inflate kmod-mac80211 kmod-macvlan kmod-mt76-core kmod-mt7603 kmod-mt76x02-common kmod-mt76x2 kmod-mt76x2-common kmod-nf-conncount kmod-nf-conntrack kmod-nf-conntrack-netlink kmod-nf-conntrack6 kmod-nf-flow kmod-nf-ipt kmod-nf-ipt6 kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-compat kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-ppp kmod-pppoe kmod-pppol2tp kmod-pppox kmod-sched-cake kmod-sched-core kmod-scsi-core kmod-slhc kmod-tun kmod-udptunnel4 kmod-udptunnel6 kmod-usb-core kmod-usb-ledtrig-usbport kmod-usb-storage kmod-usb-xhci-hcd kmod-usb-xhci-mtk kmod-usb3 kmod-wireguard libatomic1 libattr libavahi-client libavahi-dbus-support libblkid1 libblobmsg-json20230523 libc libcap libcares libcurl4 libdaemon libdbus libev libevdev libexpat libgcc1 libgmp10 libgnutls libip4tc2 libip6tc2 libipset13 libiptext-nft0 libiptext0 libiptext6-0 libiwinfo-data libiwinfo-lua libiwinfo20230701 libjson-c5 libjson-script20230523 libldns liblua5.1.5 liblucihttp-lua liblucihttp-ucode liblucihttp0 libmbedtls12 libmnl0 libncurses6 libnetfilter-conntrack3 libnettle8 libnfnetlink0 libnftnl11 libnghttp2-14 libnl-tiny1 libopenssl3 libpam libpopt0 libpthread libreadline8 librt libsodium libstdcpp6 libtasn1 libtirpc libubox20230523 libubus-lua libubus20230605 libuci-lua libuci20130104 libuclient20201210 libucode20230711 libudev-zero libusb-1.0-0 libustream-mbedtls20201210 libuuid1 libuv1  libxtables12 logd lua luci luci-app-aria2 luci-app-ddns luci-app-firewall luci-app-mwan3 luci-app-opkg luci-app-samba4 luci-app-sqm luci-base luci-compat luci-lib-base luci-lib-ip luci-lib-ipkg luci-lib-jsonc luci-lib-nixio luci-light luci-lua-runtime luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-proto-wireguard luci-ssl luci-theme-bootstrap mtd mwan3 netifd nftables-json nload odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoe ppp-mod-pppol2tp procd procd-seccomp procd-ujail px5g-mbedtls resolveip rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode rsync samba4-libs samba4-server sqm-scripts strongswan strongswan-charon strongswan-ipsec strongswan-minimal strongswan-mod-aes strongswan-mod-des strongswan-mod-gmp strongswan-mod-hmac strongswan-mod-kernel-netlink strongswan-mod-mgf1 strongswan-mod-pubkey strongswan-mod-random strongswan-mod-sha1 strongswan-mod-sha2 strongswan-mod-socket-default strongswan-mod-stroke strongswan-mod-updown strongswan-mod-vici strongswan-mod-x509 strongswan-mod-xauth-generic strongswan-mod-xcbc strongswan-swanctl tc-tiny terminfo ubi-utils ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-lua ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usbutils usign wireguard-tools wireless-regdb xl2tpd xtables-legacy xtables-nft zlib'}}
  IMAGE_BUILDER_FILE_NAME: ""
  IMAGE_BUILDER_URL: ""
  NEED_DOWNLOAD: true
  BUILD_TARGET_DIR: ""
  OUTPUT_BASE_NAME: ""

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout if needed
        uses: actions/checkout@v4
        if: ${{ env.BUILD_CUSTOM_PACKAGE }}

      - name: Setup variables
        run: |
          OPENWRT_TARGET=${{ env.OPENWRT_TARGET }}
          OPENWRT_TARGET_AS_NAME=${OPENWRT_TARGET////-}
          IMAGE_BUILDER_FILE_NAME=openwrt-imagebuilder-${{ env.OPENWRT_VERSION }}-${OPENWRT_TARGET_AS_NAME}.Linux-x86_64
          IMAGE_BUILDER_URL=${{ env.OPENWRT_DOWNLOAD_URL }}/${{ env.OPENWRT_VERSION }}/targets/$OPENWRT_TARGET/$IMAGE_BUILDER_FILE_NAME.tar.xz
          BUILD_TARGET_DIR=$IMAGE_BUILDER_FILE_NAME/bin/targets/$OPENWRT_TARGET
          OUTPUT_BASE_NAME=openwrt-${{ env.OPENWRT_VERSION }}-${OPENWRT_TARGET_AS_NAME}-${{ env.PROFILE }}
          echo "IMAGE_BUILDER_FILE_NAME=${IMAGE_BUILDER_FILE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_BUILDER_URL=${IMAGE_BUILDER_URL}" >> $GITHUB_ENV
          echo "BUILD_TARGET_DIR=${BUILD_TARGET_DIR}" >> $GITHUB_ENV
          echo "OUTPUT_BASE_NAME=${OUTPUT_BASE_NAME}" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.IMAGE_BUILDER_FILE_NAME }}
          key: ${{ env.IMAGE_BUILDER_FILE_NAME }}

      - name: Check file 
        shell: bash
        run: |
          if [[ -d ${{env.IMAGE_BUILDER_FILE_NAME}} ]]; then
            echo "NEED_DOWNLOAD=false" >> $GITHUB_ENV
          else
            echo "NEED_DOWNLOAD=true" >> $GITHUB_ENV
          fi

      - name: Download and extract image builder
        if: ${{ env.NEED_DOWNLOAD == 'true' }}
        run: |
          wget ${{ env.IMAGE_BUILDER_URL }}
          tar -J -x -f ${{env.IMAGE_BUILDER_FILE_NAME}}.tar.xz

      - name: Copy custom packages and add custom package
        if: ${{ env.BUILD_CUSTOM_PACKAGE }}
        run: |
          rsync -hav custom-packages/* ${{env.IMAGE_BUILDER_FILE_NAME}}/packages/
          echo "PACKAGES=${{env.PACKAGES}} ${{env.CUSTOM_PACKAGE_NAMES}}" >> $GITHUB_ENV

      - name: Save cache
        if: ${{ env.NEED_DOWNLOAD == 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.IMAGE_BUILDER_FILE_NAME }}
          key: ${{ env.IMAGE_BUILDER_FILE_NAME }}

      - name: Build openwrt image
        run: |
          cd ${{ env.IMAGE_BUILDER_FILE_NAME }}
          make image \
          PROFILE=${{ env.PROFILE }} \
          PACKAGES="${{ env.PACKAGES }}"
          ls -lah bin/targets/${{ env.OPENWRT_TARGET }}

      - name: Upload sysupgrade output
        if: ${{ github.event_name == 'workflow_dispatch' && env.UPLOAD_SYSUPGRADE_ONLY }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_BASE_NAME }}-sysupgrade
          path: |
            ${{ env.BUILD_TARGET_DIR }}/${{ env.OUTPUT_BASE_NAME }}-squashfs-sysupgrade.bin
            ${{ env.BUILD_TARGET_DIR }}/profiles.json
            ${{ env.BUILD_TARGET_DIR }}/sha256sums
          retention-days: 5

      - name: Upload all output
        if: ${{ github.event_name == 'workflow_dispatch' && !env.UPLOAD_SYSUPGRADE_ONLY }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_BASE_NAME }}
          path: ${{ env.BUILD_TARGET_DIR }}
          retention-days: 5

      - name: Create release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          artifacts: "${{ env.BUILD_TARGET_DIR }}/*"
          body: |
            ### Build information:
            * Build target: **${{ env.OPENWRT_TARGET }}**
            * Device profile: **${{ env.PROFILE }}**
            * Openwrt version: **${{ env.OPENWRT_VERSION }}**
            * Image builder downloaded from: ${{ env.IMAGE_BUILDER_URL }}
            <details>
            <summary>Installed package</summary>

            ```
            ${{ env.PACKAGES }}
            ```
            </details>

